apiVersion: v1
kind: Service
metadata:
  name: postgres-service 
  labels:
    name: postgres-pod
    app: demo-app
spec:
  selector:
    name: postgres-pod
    app: demo-app
  ports:
  - port: 5432
    targetPort: 5432
