apiVersion: v1
kind: PersistentVolume
metadata:
  name: st-voting
  namespace: voting-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/chr/kube-practice/votingapp/voting-app-storage/


