apiVersion: v1
kind: Service
metadata:
  name: redis-ser
  labels:
    name: redis-ser
    app: demo-app
spec:
  selector:
    name: redis-pod
    app: demo-app
  ports:
  - port: 6379
    targetPort: 6379
