apiVersion: v1
kind: Service
metadata:
  name: res-ser
  labels:
    name: res-ser
    app: demo-app
spec:
  type:  NodePort
  selector:
    name: res-pod
    app: demo-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005
