apiVersion: apps/v1
kind: Deployment
metadata:
  name: res-deploy
  labels:
    name: res-deploy
    app: demo-app
spec:
  selector:
    matchLabels:
      name: res-pod
      app: demo-app
  template:
    metadata:
      name: res-pod
      labels:
        name: res-pod
        app: demo-app
    spec:
      containers:
      - name: res-app
        image: kodekloud/examplevotingapp_result:v1
        ports:
        - containerPort: 80
