apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deploy
  labels:
    name: vote-deploy
    app: demo-app
spec:
  selector:
    matchLabels:
      name: vote-pod
      app: demo-app
  template:
    metadata:
      name: vote-pod
      labels:
        name: vote-pod
        app: demo-app
    spec:
      containers:
      - name: vote-app
        image: kodekloud/examplevotingapp_vote:v1
        ports:
        - containerPort: 80
